* jzon-mop

Tested on ECL and SBCL.

** Description
JSON source to object mapping, using ~com.inuoe.jzon~. It is primarily meant as a
non-intrusive wrapper for existing classes and known sources. Surely, hash-tables are
fine, but I often like classes better. So here's a small MOP library that allows JSON
parsing directly to objects instead of hash-tables.

Serializing is quite easy with ~jzon~, and parsing is as well - unless you want
something different than hash-tables for objects. This approach makes parsing
(mostly) interchangeable with calling a regular ~jzon:parse~, but directly converts
the JSON object tokens into the expected lisp objects.
** Install
*** Qlot
#+BEGIN_SRC bash
  qlot add github jmeissen/jzon-mop
#+END_SRC

After installing, run in the qlot environment:
#+BEGIN_SRC lisp
  (ql:quickload :jzon-mop)
#+END_SRC

** Usage

Essentially:
- Metaclass ~jzon-mop:jzon-mop-model-class~
- Parsing with ~jzon-mop:parse~

#+BEGIN_SRC lisp
  (in-package #:cl-user)

  (defvar *my-source* "{\"data\": [{\"this_val\": 1, \"that_val\": 2}]}"
    "A string, stream, pathname, etc.")

  (defclass some-listed-object ()
    (this-val
     that-val)
    (:metaclass jzon-mop:jzon-mop-model-class))

  (defclass my-parseable ()
    ((data
      :type vector
      :subtype some-listed-object))
    (:metaclass jzon-mop:jzon-mop-model-class))

  (jzon-mop:parse *my-source* 'my-parseable)
  ;; => #<MY-PARSEABLE>
#+END_SRC

As the example above shows, parsing arrays of objects is possible through ~:subtype~.

A default assumption is that JSON-keys are snake_cased. However, your JSON may not
behave such as this exactly, or at all. By default, ~symbol-munger~ is installed
which handles =snake_case= to =kebab-case-slot-name= conversion. Since JSON-keys are
dynamically mapped to their corresponding =kebab-case-slot-name=, you may provide a
custom ~:key-parser~ which takes precedence for the particular class over the default
function defined in ~*default-key-parser*~.

For example:

#+BEGIN_SRC lisp
  (defvar *my-source* "{\"underscored_name\": \"some value\", \"fromCamelCase\": \"some other value\"}")

  (defun weird-key-parser (string-arg)
    (if (string= "fromCamelCase" string-arg)
        (symbol-munger:camel-case->lisp-symbol string-arg)
        (symbol-munger:underscores->lisp-symbol string-arg)))

  (defclass some-weird-keys ()
    ((underscored-name
      :initarg :underscored-name
      :accessor some-weird-keys-underscored-name)
     (from-camel-case
      :initarg :from-camel-case
      :accessor some-weird-keys-from-camel-case))
    (:metaclass jzon-mop:jzon-mop-model-class)
    (:key-parser (lambda (string-arg)
                   (if (string= "fromCamelCase" string-arg)
                       (symbol-munger:camel-case->lisp-symbol string-arg)
                       (symbol-munger:underscores->lisp-symbol string-arg)))))


  (jzon-mop:parse *my-source* 'some-weird-keys)
  ; => #<SOME-WEIRD-KEYS>
#+END_SRC

So in this instance, "fromCamelCase" is parsed correctly even though the default is
snake_case is default.

*** Customizing the ~:key-parser~
The default object key parser is defined in ~jzon-mop:*default-key-parser*~. This
function-symbol takes two arguments: ~key-string~ and
~package~. ~*default-key-parser*~ may be overwritten, but for a more specific
functioning, it may also be supplied per-class in the class-option ~:key-parser~.

The class-option ~:key-parser~ can be a symbol, a lambda, or nil. Note that values
are not evaluated at compile-time, meaning that the lambda is eval'd at runtime. It's
only here for convenience, but it is probably not fast. Providing a symbol that
references a predefined function is probably a better choice.

*** Quirks
Unless specified, the JSON-objects will be parsed as hash-tables, so mixing these is
fine. However, if you leave an object as hash-table, then there's no way to parse its
children into objects.

Finally, the parser knows what to do when encountering top-level arrays. However, when
the children differ in object type, then there's an unresolvable problem.

That's it. Happy hacking!

** Contributing
*** Run tests
#+BEGIN_SRC shell
  qlot install
  qlot exec sbcl --disable-debugger --eval '(asdf:test-system :jzon-mop)' --quit
#+END_SRC
